name = "my_dojo_project"
version = "0.1.0"

[[lean_lib]]
name = "MyDojoProject"

# This section tells Lake that your project depends on mathlib
[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4.git", rev = "bc70da8fd1d791a61ad9089b6a8da1dc671b9198" }